### ISSUE TITLE
periodically call /v1/receive to keep client in sync

### ISSUE THREAD

**Issue by makefu** [bbernhard/pysignalclirestapi#1]
Hi, i've tested the library with home-assistant but after a couple of hours the send requests stopped working.

According to the signal-rest services the /v1/receive endpoind needs to be polled periodically in order to keep the client in sync.
It would be great if the library would perform the sync action to keep signal working over a longer period.
Cheers!

**Comment by makefu** [comment]
i will open this with home-assistant core, thanks!

**Comment by bbernhard** [comment]
just fyi: there's already a similar discussion ongoing here: https://github.com/home-assistant/core/issues/48637

**Comment by makefu** [comment]
yep, i actually created this issue as i thought it better fits there. it is not really fitting to your library but it should be performed by the home-assistant itself.
