### ISSUE TITLE
futures.util does not exist

### ISSUE THREAD

**Issue by alexyao2015** [bbernhard/pysignalclirestapi#5]
Futures.util does not exist in python 3 and there are no requirements to install such a dependency. Additionally, python 2.7 is long deprecated at this point, and there doesn't seem to be much reach to continue to support it.

**Comment by bbernhard** [comment]
> Futures.util does not exist in python 3

Are you sure? 

```
Python 3.7.5 (default, Dec  9 2021, 17:04:37) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import future.utils
>>> 
```
But you are totally right, the dependency is missing in the `setup.py` (also `requests` should probably be listed there)

**Comment by alexyao2015** [comment]
I was getting import errors in 3.9 when I ran a home assistant dev instance, specifically pertaining to this import.

**Comment by alexyao2015** [comment]
Sorry I was specifically referring to futures.util existing as a standard lib instead of an external dependency.

**Comment by bbernhard** [comment]
Should be fixed with the newest version

**Comment by alexyao2015** [comment]
Thanks!
